name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::471112884093:role/github-actions-wallacevilela7-pipeline"
      aws-region: "us-east-1"
      aws-statefile-s3-bucket: "wallacevilela7-us-east-1-terraform-state-file"
      aws-lock-dynamodb-table: "wallacevilela7-us-east-1-terraform-lock"